services:
  inviseobox:
    image: ghcr.io/inviseo/inviseobox:latest
    container_name: inviseobox
    privileged: true
    user: root
    restart: always
    pull_policy: always
    environment:
      - token=XXXXXXXXXXXXXXXXXXX
      - interval=1800
      - url=XXXXXXXXXXXXXXXXXXX
    # On monte le dossier /dev sur le container pour pouvoir utiliser les devices USB
    volumes:
      - /dev:/dev

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    command: --interval 5 --debug  --cleanup inviseobox
