services:
  inviseobox:
    image: ghcr.io/inviseo/inviseobox:latest
    container_name: inviseobox
    privileged: true
    user: root
    restart: always
    pull_policy: always
    environment:
      - token=XXXXXXXXXXXXXXXXXXX
      - url=XXXXXXXXXXXXXXXXXXX
    volumes:
      - /dev:/dev

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    command: --interval 5 --debug  --cleanup inviseobox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
